### ISSUE TITLE
// not recognized as single line comment

### ISSUE THREAD

**Issue by BartJolling** [florianbaer/pb-syntax#1]
// Using Visual Studio Code 1.26.1 on x64

/*
This is correctly highlighted as a comment
*/

// This is not correctly highlighted as a comment

// The double quote " that should be commented out, still opens a string...
The code here is considered part of the string that is started on the commented out line.

**Comment by BartJolling** [comment]
I @florianbaer , I noticed that you added support for single line comments in commit 77edcba on the 24th of April. In the marketplace however, it's still the version of the 18th of April: https://marketplace.visualstudio.com/items?itemName=florianbaer.pb-syntax

Any plans on publishing the latest fixes on the marketplace?

For other people with the same issue, I manually copied the content of powerbuilder.tmLanguage.json into this file in my extensions folder: <install-folder>\Microsoft VS Code\data\extensions\florianbaer.pb-syntax-0.1.0\syntaxes\powerbuilder.tmLanguage.json

**Comment by florianbaer** [comment]
Hi @BartJolling 
I had some problems with the access token for VSMP

I updated the extension now, can you tell me if it worked for you?

Thanks for your work🚀 👍

**Comment by BartJolling** [comment]
I loaded version 0.2.0 in VS Code. First spot checks confirm everything works as expected. Thanks
